### PR TITLE
Team Name : Block Developer

### PR DESCRIPTION
**Pull request by ProgrammingPirates**
@simarpreetsingh-019  I have made this new PR please sir merge this

### CODE REVIEW

**Comment by simarpreetsingh-019** [comment]
its creating some merge conflict , lets do a quick fix : 
copy the readme file from our repo's [readme](https://github.com/Tezos-India/TezAsia-2k23/blob/main/README.md) 
add this file outside of your project folder , and redo the PR.

**Comment by ProgrammingPirates** [comment]
Ok sir thanks

**Comment by simarpreetsingh-019** [comment]
@ProgrammingPirates 1 more suggestion :  Your demo video show the wallet connect with Metamask . can you try to add ss of wallet connect with Tezos based wallets ?

**Comment by ProgrammingPirates** [comment]
Ok sir

**Pull request closed without merging**
